"""Named color presets for the rail navigation sidebar.

Each preset maps a subset of the settings keys (see
:mod:`streamlit_rail_nav.settings`) to color values. Apply a preset by merging
it over a settings dict before calling ``render()``.
"""

from __future__ import annotations

THEME_PRESETS: dict[str, dict[str, str]] = {
    "Anthropic Style": {
        "sidebar_bg": "#e8e7dd",
        "sidebar_text_color": "#3d3a2a",
        "sidebar_icon_color": "#3d3a2a",
        "sidebar_hover_bg": "#BB5A38",
        "sidebar_hover_text_color": "#D3D2CA",
        "sidebar_active_bg": "#BB5A38",
        "sidebar_focus_outline": "#BB5A38",
        "sidebar_separator_color": "#3D3A2A",
    },
    "Ocean Palette": {
        "sidebar_bg": "#395B77",
        "sidebar_text_color": "#F6F7EF",
        "sidebar_icon_color": "#F6F7EF",
        "sidebar_hover_bg": "#7BA8CA",
        "sidebar_hover_text_color": "#395B77",
        "sidebar_active_bg": "#A8DAFF",
        "sidebar_focus_outline": "#A8DAFF",
        "sidebar_separator_color": "#7BA8CA",
    },
    "Slate Orange": {
        "sidebar_bg": "#263741",
        "sidebar_text_color": "#EEF2F1",
        "sidebar_icon_color": "#EEF2F1",
        "sidebar_hover_bg": "#EA9216",
        "sidebar_hover_text_color": "#263741",
        "sidebar_active_bg": "#C3CCD2",
        "sidebar_focus_outline": "#C3CCD2",
        "sidebar_separator_color": "#C3CCD2",
    },
    "Navy Gold Aqua": {
        "sidebar_bg": "#083A4F",
        "sidebar_text_color": "#E5E1DD",
        "sidebar_icon_color": "#E5E1DD",
        "sidebar_hover_bg": "#407E8C",
        "sidebar_hover_text_color": "#E5E1DD",
        "sidebar_active_bg": "#A58D66",
        "sidebar_focus_outline": "#A58D66",
        "sidebar_separator_color": "#C0D5D6",
    },
    "Cadet Yam": {
        "sidebar_bg": "#313841",
        "sidebar_text_color": "#EEEEEE",
        "sidebar_icon_color": "#EEEEEE",
        "sidebar_hover_bg": "#3A4750",
        "sidebar_hover_text_color": "#EEEEEE",
        "sidebar_active_bg": "#EA9216",
        "sidebar_focus_outline": "#EA9216",
        "sidebar_separator_color": "#3A4750",
    },
    "Matcha Almond": {
        "sidebar_bg": "#1A3636",
        "sidebar_text_color": "#D6BD98",
        "sidebar_icon_color": "#D6BD98",
        "sidebar_hover_bg": "#40534C",
        "sidebar_hover_text_color": "#D6BD98",
        "sidebar_active_bg": "#677D6A",
        "sidebar_focus_outline": "#677D6A",
        "sidebar_separator_color": "#40534C",
    },
    "Black & White (Light)": {
        "sidebar_bg": "#EBEBEB",
        "sidebar_text_color": "#111111",
        "sidebar_icon_color": "#111111",
        "sidebar_hover_bg": "#F2F2F2",
        "sidebar_hover_text_color": "#111111",
        "sidebar_active_bg": "#E6E6E6",
        "sidebar_focus_outline": "#111111",
        "sidebar_separator_color": "#D0D0D0",
    },
    "Black & White (Dark)": {
        "sidebar_bg": "#2E333A",
        "sidebar_text_color": "#EBEBEB",
        "sidebar_icon_color": "#EBEBEB",
        "sidebar_hover_bg": "#3B4048",
        "sidebar_hover_text_color": "#EBEBEB",
        "sidebar_active_bg": "#3B4048",
        "sidebar_focus_outline": "#EBEBEB",
        "sidebar_separator_color": "#4A4F57",
    },
    "HALO Core Palette": {
        "sidebar_bg": "#313841",
        "sidebar_text_color": "#EEEEEE",
        "sidebar_icon_color": "#EEEEEE",
        "sidebar_hover_bg": "#3A4750",
        "sidebar_hover_text_color": "#EEEEEE",
        "sidebar_active_bg": "#EA9216",
        "sidebar_focus_outline": "#EA9216",
        "sidebar_separator_color": "#3A4750",
        "sidebar_separator_color_light": "#3A4750",
        "sidebar_separator_color_dark": "#3A4750",
        "sidebar_rail_bg": "#313841",
        "sidebar_rail_text_color": "#EEEEEE",
        "input_bg": "#313841",
        "input_text_color": "#EEEEEE",
        "input_border_color": "#3A4750",
        "input_border_hover": "#EA9216",
        "input_hover_bg": "#3A4750",
        "input_focus_outline": "#EA9216",
        "theme_mode": "dark",
        "logo_src": "assets/logo_dark.png",
    },
}
